# Generated by Django 5.1.7 on 2025-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('body_temperature', models.FloatField()),
                ('spo2', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('respiration_rate', models.IntegerField()),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
            ],
        ),
    ]
